### ISSUE TITLE
Generated PDF lists wrong organization as copyright owner

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#157]
Every other page in the PDF incorrectly mentions the first organisation listed in the Submitting Organisations list as the copyright owner.

In most cases (more than 90% of cases) the copyright owner will be Open Geospatial Consortium.

There should be a document property for setting the copyright owner.

e.g.
<img width="993" alt="image" src="https://user-images.githubusercontent.com/11865/85968607-1dba5480-b9f8-11ea-8a9d-e43fae2b50fb.png">

Originally from: https://github.com/opengeospatial/ogc-metanorma-testing/issues/26

**Comment by ghobona** [comment]
This appears to have been fixed.

**Comment by Intelligent2013** [comment]
In PDF is not fixed yet. In waiting of https://github.com/metanorma/metanorma-ogc/issues/158.

**Comment by opoudjis** [comment]
@Intelligent2013 And #158 does not require any action from you, the action is in Asciidoctor

**Comment by ronaldtse** [comment]
@opoudjis is this fixed or not fixed? This is from June. We can't wait for Asciidoctor.

**Comment by ronaldtse** [comment]
Looks like it's fixed in https://github.com/metanorma/metanorma-ogc/pull/178 . Closing.

**Comment by ronaldtse** [comment]
@Intelligent2013 are you using the fix from #178 now? If not we need to reopen this. Thanks!

**Comment by ronaldtse** [comment]
Actually let me reopen this, @Intelligent2013 if it's fixed please close it.

**Comment by Intelligent2013** [comment]
Fixed. Now the copyright owner for PDF getting from `bibdata/copyright/owner/organization/name`.

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
